NewsApp/Controllers/DisplayArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NewsApp.DAL;
using NewsApp.Models;
using Newtonsoft.Json;

namespace NewsApp.Controllers
{
    public class DisplayArticlesController : Controller
    {
        private EfDbContext db = new EfDbContext();
        private DisplayArticle displayArticle = new DisplayArticle();

        [Authorize(Roles = "Admin")]
        public ActionResult UpdateDatabase()
        {
            ResponseNewsAppModels jsonModel = new ResponseNewsAppModels();
            List<DisplayArticle> articleList = new List<DisplayArticle>();
            List<Category> categoryList = db.Categories.ToList();
            foreach (var category in categoryList)
            {
                string jsonObject = jsonModel.TransportJsonNewsWithApp(category.name);
                IEnumerable<NewArticle> listArticle = JsonConvert.DeserializeObject<IEnumerable<NewArticle>>(jsonObject) as IEnumerable<NewArticle>;

                foreach (var article in listArticle)
                {
                    displayArticle = new DisplayArticle
                    {
                        author = article.newAuthor,
                        title = article.newTitle,
                        description = article.newDescription,
                        url = article.newUrl,
                        urlToImage = article.newUrlToImage,
                        publishetAt = article.newPublishetAt,
                        source = article.newSource.newName,
                        idCateogry = category.idCategory
                    };

                    articleList.Add(displayArticle);
                }
            }
            db.Articles.AddRange(articleList);
            db.SaveChanges();
            var message = "Zaktualizowano wszystkie artykuły ";
            return RedirectToAction("ControlPanel", new { information = message });
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ClearDatabase()
        {
            db.Database.ExecuteSqlCommand("TRUNCATE TABLE [DisplayArticle]");
            db.SaveChanges();

            var message = " Usunięto wszystkie artykuły";
            return RedirectToAction("ControlPanel", new { information = message });
        }

        private int selectCategory(string category)
        {
            var searchCategoryId = from categories in db.Categories
                                   where categories.name == category
                                   select categories.idCategory;

            return searchCategoryId.FirstOrDefault();
        }

        [Authorize(Roles = "User, Admin")]
        public ActionResult Show()
        {
            string category = Request.QueryString["category"];
            int idCategory = 0;
            if (selectCategory(category) == 0)
                idCategory = 1;
            else idCategory = selectCategory(category);

            var selectCategoryArticles = db.Articles
              .Where(x => x.idCateogry == idCategory).ToList();
            return View(selectCategoryArticles);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ControlPanel()
        {
            string category = Request.QueryString["category"];
            ResponseNewsAppModels jsonModel = new ResponseNewsAppModels();
            int idCategory = selectCategory(category);
            if (selectCategory(category) != 0)
            {
                var searchCategoryName = from categories in db.Categories
                                         where categories.idCategory == idCategory
                                         select categories.name;

                db.Articles.RemoveRange(db.Articles.Where(x => x.idCateogry == idCategory));
                db.SaveChanges();

                string jsonObject = jsonModel.TransportJsonNewsWithApp(Request.QueryString["category"]);
                IEnumerable<NewArticle> listArticle = JsonConvert.DeserializeObject<IEnumerable<NewArticle>>(jsonObject) as IEnumerable<NewArticle>;

                foreach (var article in listArticle)
                {
                    displayArticle.author = article.newAuthor;
                    displayArticle.title = article.newTitle;
                    displayArticle.description = article.newDescription;
                    displayArticle.url = article.newUrl;
                    displayArticle.urlToImage = article.newUrlToImage;
                    displayArticle.publishetAt = article.newPublishetAt;
                    displayArticle.source = article.newSource.newName;
                    displayArticle.idCateogry = idCategory;

                    db.Articles.Add(displayArticle);
                    db.SaveChanges();
                    db.Database.Connection.Close();
                }
            }
            return View(db.Articles.ToList());
        }
    }
}

NewsApp/Views/DisplayArticles/ControlPanel.cshtml
@model IEnumerable<NewsApp.Models.DisplayArticle>

@{
    ViewBag.Title = "ControlPanel";
}


<br />
<h2>Panel administracyjny</h2>
<br />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("button").click(function () {
            $("#tblMain").show();
            $("#idB").hide();

        });
    });
</script>

<center><img id="tblMain" style="display: none;" src="@Url.Content("~/Content/Images/load.gif")" width="120" height="120" /></center>

@if (@Request.Params["information"] == null && @Request.Params["category"] != null)
{
    <div class="alert alert-dismissible alert-info" id="idB">
        <button type="button" class="close" data-dismiss="alert">&times;</button>


       Zaktualizowano kategorię: <strong>@Request.Params["category"]</strong>
    </div>
}
@if (@Request.Params["information"] != null && @Request.Params["category"] == null)
{
    <div class="alert alert-dismissible alert-info" id="idB">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>@Request.Params["information"]</strong>
    </div>
}
<center><img id="tblMain" style="display: none;" src="@Url.Content("~/Content/Images/load.gif")" /></center>
<div class="card border-primary mb-3" style="max-width: 200rem;">
    <div class="card-header">Zaktualizuj</div>
    <div class="card-body">
        <button type="button" id="btn" class="btn btn-primary" onclick="location.href='@Url.Action("UpdateDatabase", "DisplayArticles")'">Wszystko</button>
        <br><br><p class="card-title">pojedynczą kategorię:</p>
        <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "top" })'">Top</button>
        <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "business" })'">Biznes</button>
        <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "entertainment" })'">Rozrywka</button>
        <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "health" })'">Zdrowie</button>
        <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "science" })'">Nauka</button>
        <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "sports" })'">Sport</button>
        <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "technology" })'">Technologia</button>
    </div>
</div>

<div class="card border-primary mb-3" style="max-width: 200rem;">
    <div class="card-header">Usuń</div>
    <div class="card-body">
        <button type="button" class="btn btn-primary" id="btnClear" onclick="location.href='@Url.Action("ClearDatabase", "DisplayArticles")'">Wszystko</button>
    </div>
</div>

NewsApp/Views/DisplayArticles/Index.cshtml
@model IEnumerable<NewsApp.Models.DisplayArticle>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<button type="button" onclick="location.href='@Url.Action("ClearDatabase", "DisplayArticles")'">Wyczyść baze</button>
<button type="button" onclick="location.href='@Url.Action("UpdateDatabase", "DisplayArticles")'">Pobierz dane</button>
<button type="button" onclick="location.href='@Url.Action("Show", "DisplayArticles")'">User</button>
<button type="button" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles")'">Admin</button>

<button type="button" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "top" })'">Top</button>
<button type="button" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "business" })'">Biznes</button>
<button type="button" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "entertainment" })'">Rozrywka</button>
<button type="button" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "health" })'">Zdrowie</button>
<button type="button" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "science" })'">Nauka</button>
<button type="button" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "sports" })'">Sport</button>
<button type="button" onclick="location.href='@Url.Action("ControlPanel", "DisplayArticles", new { category = "technology" })'">Technologia</button>

<p>
    @Html.ActionLink("Wyczyść baze", "ClearDatabase")
</p>
<p>
    @Html.ActionLink("Pobierz dane", "UpdateDatabase")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.urlToImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.publishetAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.source)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.url)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.urlToImage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.publishetAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.source)
            </td>

        </tr>
    }

</table>

NewsApp/Views/DisplayArticles/Show.cshtml
@model IEnumerable<NewsApp.Models.DisplayArticle>

@{
    ViewBag.Title = "Show";
}
<br />
Kategorie:
<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Show", "DisplayArticles", new { category = "top" })'">Top</button>
<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Show", "DisplayArticles", new { category = "business" })'">Biznes</button>
<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Show", "DisplayArticles", new { category = "entertainment" })'">Rozrywka</button>
<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Show", "DisplayArticles", new { category = "health" })'">Zdrowie</button>
<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Show", "DisplayArticles", new { category = "science" })'">Nauka</button>
<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Show", "DisplayArticles", new { category = "sports" })'">Sport</button>
<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Show", "DisplayArticles", new { category = "technology" })'">Technologia</button>
<br /><br />

<table class="table table-hover">
    @foreach (var item in Model)
    {
        <tr class="table-primary">
            <td style="float:none">
                @if (!String.IsNullOrEmpty(item.urlToImage))
                {
                    <a href="@Html.DisplayFor(modelItem => item.url)">
                        <img src="@Url.Content(item.urlToImage)" alt="" width="150" height="100" />
                    </a>
                }
                @if (item.urlToImage == null)
                {
                    @Html.DisplayFor(modelItem => item.urlToImage)
                }
            </td>
            <td>
                <a href="@Html.DisplayFor(modelItem => item.url)">
                    <p style=" color:black; font-size: 18px;"><b>@Html.DisplayFor(modelItem => item.title)</b></p>
                    <p style=" color:black; font-size: 15px;">@Html.DisplayFor(modelItem => item.description)</p>
                </a>
                <p style="font-size: 10px;">Źródło: @Html.DisplayFor(modelItem => item.source)</p>
            </td>
        </tr>
    }
</table>